In [1]:
import numpy as np

In [2]:
l = list( range( 10 ) )
print( l )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
# Selecionando uma "fatia" da lista:

# Removendo n elementos do fim:
n = 3
print( l[ : -n ] )
print( l[ : len( l ) - n ] )

[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6]


In [4]:
# Removendo n elementos do começo:
n = 3
print( l[ n : ] )

[3, 4, 5, 6, 7, 8, 9]


In [5]:
# Saltando n elementos:
n = 2
print( l[ : : 2 ] )
print( l[ 1 : : 2 ] )

[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]


In [6]:
# Indo de trás pra frente:
print( l[ : : -1 ] )

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [7]:
# Indo de trás pra frente:
print( l[ -1 : 2 : -1 ] )

[9, 8, 7, 6, 5, 4, 3]


In [8]:
A = np.arange( 1.0, 17.0 ).reshape( ( 4, 4 ) )
print( A )

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [9]:
print( A[ : : , 1 : : 2 ] )

[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]
 [14. 16.]]


In [10]:
print( A[ 1 : 3, 1 : ] )

[[ 6.  7.  8.]
 [10. 11. 12.]]


In [11]:
print( A[ : : 3, 1 : : 2 ] )

[[ 2.  4.]
 [14. 16.]]


In [12]:
print( A[ :, [ 0, 3, 2 ] ] )

[[ 1.  4.  3.]
 [ 5.  8.  7.]
 [ 9. 12. 11.]
 [13. 16. 15.]]
