In [1]:
import numpy as np
import time

In [2]:
def triu_solve( U, b ):
    
    n = U.shape[ 0 ]    
    x = np.empty( ( b.shape[ 0 ], ) )
    
    for i in range( n - 1, -1, -1 ):
        
        x[ i ] = ( b[ i ] - np.sum( U[ i, i + 1 : n ] * x[ i + 1 : n ] ) ) / U[ i, i ]
        
    return x

In [3]:
U = np.array(
    [
        [ 1.0, 1.0,  1.0,  1.0 ],
        [ 0.0, 1.0,  2.0,  3.0 ],
        [ 0.0, 0.0, -1.0, -4.0 ],
        [ 0.0, 0.0,  0.0,  3.0 ]
    ]
)
b_til = np.array( [ 1.0, 1.0, 0.0, 3.0 ] )

x = triu_solve( U, b_til )

print( x )

[-2.  6. -4.  1.]


In [4]:
A = np.array(
    [
        [ 1.0, 1.0, 1.0, 1.0 ],
        [ 1.0, 2.0, 3.0, 4.0 ],
        [ 1.0, 3.0, 4.0, 3.0 ],
        [ 1.0, 1.0, 0.0, 0.0 ]
    ]
)

b = np.array( [ 1.0, 2.0, 3.0, 4.0 ] )

print( A @ x )

[1. 2. 3. 4.]


In [5]:
def elimina( A, b ):
    
    n = A.shape[ 0 ]
    
    for i in range( n ):
        for k in range( i + 1, n ):
            
            alpha = A[ k, i ] / A[ i, i ]
            
            for j in range( i, n ):
                A[ k, j ] = A[ k, j ] - alpha * A[ i, j ]
                
            b[ k ] = b[ k ] - alpha * b[ i ]

In [6]:
A_copy = A.copy()
b_copy = b.copy()

elimina( A_copy, b_copy )
x = triu_solve( A_copy, b_copy )

print( A_copy, b_copy, x )

[[ 1.  1.  1.  1.]
 [ 0.  1.  2.  3.]
 [ 0.  0. -1. -4.]
 [ 0.  0.  0.  3.]] [1. 1. 0. 3.] [-2.  6. -4.  1.]


In [7]:
A_chata = np.array( [ [ 0.0, 1.0 ], [ 1.0, 0.0 ] ] )
print( A_chata )
print( elimina( A_chata, np.array( [ 1.0, 2.0 ] ) ) )
print( A_chata )

[[0. 1.]
 [1. 0.]]
None
[[  0.   1.]
 [ nan -inf]]


/home/elias/.local/lib/python3.6/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  
/home/elias/.local/lib/python3.6/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()


In [8]:
def lin_solve( A, b ):
    
    A_copy = A.copy()
    b_copy = b.copy()
    
    elimina( A_copy, b_copy )
    
    return triu_solve( A_copy, b_copy )

In [9]:
n = 300
A = np.random.normal( size = ( n, n ) )
b = np.random.normal( size = ( n, ) )

np.linalg.cond( A )

2655.643881855042

In [10]:
start = time.time()
x = lin_solve( A, b )
print( time.time() - start )

print( np.max( np.abs( A @ x - b ) ) )

5.296715974807739
2.7619684317414794e-11


In [11]:
def elimina_II( A, b ):
    
    n = A.shape[ 0 ]
    
    for i in range( n ):
        for k in range( i + 1, n ):
            
            alpha = A[ k, i ] / A[ i, i ]
            
            A[ k, i : n ] = A[ k, i : n ] - alpha * A[ i, i : n ]
                
            b[ k ] = b[ k ] - alpha * b[ i ]
            
def lin_solve_II( A, b ):
    
    A_copy = A.copy()
    b_copy = b.copy()
    
    elimina_II( A_copy, b_copy )
    
    return triu_solve( A_copy, b_copy )

start = time.time()
x_II = lin_solve_II( A, b )
print( time.time() - start )

print( np.max( np.abs( A @ x_II - b ) ) )

0.25220465660095215
2.7619684317414794e-11


In [12]:
n = 1000
A = np.random.normal( size = ( n, n ) )
b = np.random.normal( size = ( n, ) )

print( np.linalg.cond( A ) )

def elimina_III( A, b ):
    
    n = A.shape[ 0 ]
    
    for i in range( n ):
        alpha = A[ i + 1 : n, [ i ] ] / A[ i, i ]

        A[ i + 1 : n, i : n ] = A[ i + 1 : n, i : n ] - alpha * A[ i, i : n ]

        b[ i + 1 : n ] = b[ i + 1 : n ] - np.squeeze( alpha ) * b[ i ]
            
def lin_solve_III( A, b ):
    
    A_copy = A.copy()
    b_copy = b.copy()
    
    elimina_III( A_copy, b_copy )
    
    return triu_solve( A_copy, b_copy )

start = time.time()
x_III = lin_solve_III( A, b )
print( time.time() - start )

print( np.max( np.abs( A @ x_III - b ) ) )

4509.054114678426
1.2976608276367188
1.0559580987390405e-09


In [13]:
# Broadcasting
print( np.ones( ( 5, 1 ) ) * np.ones( ( 1, 3 ) ) )

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
