In [1]:
import numpy as np
import time

def triu_solve( U, b ):
    
    n = U.shape[ 0 ]    
    x = np.empty( ( b.shape[ 0 ], ) )
    
    for i in range( n - 1, -1, -1 ):
        
        x[ i ] = ( b[ i ] - np.sum( U[ i, i + 1 : n ] * x[ i + 1 : n ] ) ) / U[ i, i ]
        
    return x

def elimina( A, b ):
    
    n = A.shape[ 0 ]
    
    for i in range( n ):
        alpha = A[ i + 1 : n, [ i ] ] / A[ i, i ]

        A[ i + 1 : n, i : n ] = A[ i + 1 : n, i : n ] - alpha * A[ i, i : n ]

        b[ i + 1 : n ] = b[ i + 1 : n ] - np.squeeze( alpha ) * b[ i ]
            
def lin_solve( A, b ):
    
    A_copy = A.copy()
    b_copy = b.copy()
    
    elimina( A_copy, b_copy )
    
    return triu_solve( A_copy, b_copy )

In [2]:
def elimina_pp( A, b ):
    
    n = A.shape[ 0 ]
    
    for i in range( n ):

        I = np.argmax( np.abs( A[ i :, i ] ) ) + i
    
        tmp = A[ i, : ].copy()
        A[ i, : ] = A[ I, : ]
        A[ I, : ] = tmp

        tmp = b[ i ].copy()
        b[ i ] = b[ I ]
        b[ I ] = tmp

        alpha = A[ i + 1 : n, [ i ] ] / A[ i, i ]

        A[ i + 1 : n, i : n ] = A[ i + 1 : n, i : n ] - alpha * A[ i, i : n ]

        b[ i + 1 : n ] = b[ i + 1 : n ] - np.squeeze( alpha ) * b[ i ]
        
def lin_solve_pp( A, b ):
    
    A_copy = A.copy()
    b_copy = b.copy()
    
    elimina_pp( A_copy, b_copy )
    
    return triu_solve( A_copy, b_copy )

In [3]:
n = 500
A = np.random.normal( size = ( n, n ) )
b = np.random.normal( size = ( n, ) )

# np.linalg.cond( A )

In [4]:
start = time.time()
x = lin_solve( A, b )
print( time.time() - start )

print( np.max( np.abs( A @ x - b ) ) )

0.09989619255065918
3.194343678458722e-10


In [5]:
start = time.time()
x_pp = lin_solve_pp( A, b )
print( time.time() - start )

print( np.max( np.abs( A @ x_pp - b ) ) )

0.11841225624084473
6.090683513093609e-13


In [6]:
print( np.max( np.abs( A @ x - b ) ) / np.max( np.abs( A @ x_pp - b ) ) )

524.463908129785


In [7]:
B = np.ones( ( 5, 5 ) )
tmp = B[ 1, : ]
tmp[ : ] = 2

print( B )
print( tmp )

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[2. 2. 2. 2. 2.]


In [8]:
l1 = [ 1, 2, 3 ]
l2 = [ 'a', 'b', 'c' ]
l3 = [ l1, l2 ]

l3[ 0 ][ 0 ] = 5

print( l1 )

l4 = l1
l4[ 1 ] = 6

print( l1 )

[5, 2, 3]
[5, 6, 3]
